lab10/Feeder35/Feeder35/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^login/',include('login.urls')),
    url(r'^adminuser/',include('adminuser.urls')),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'', include('social_auth.urls')),
]

lab10/Feeder35/login/urls.py
from django.conf.urls import url
from login.views import loginpage,registerpage

urlpatterns = [
    url(r'^$',loginpage,name='login'),
    url(r'^register/$',registerpage,name='registerpage'),
]

lab10/Feeder35/adminuser/models.py
from django.db import models

# Create your models here.

lab10/Feeder35/login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators  import RegexValidator

Gender_choices = (("MALE", "Male"),("FEMALE", "Female"),)
DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

class logindatabase(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,)
    Gender=models.CharField(max_length = 10,choices=Gender_choices,default="Male")
    Birthdate = models.DateField()

lab10/Feeder35/login/forms.py
from django import forms
from login.models import logindatabase
from django.contrib.auth.models import User

dateformat=[
    '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', # '2006-10-25', '10/25/2006', '10/25/06'
    '%b %d %Y', '%b %d, %Y',            # 'Oct 25 2006', 'Oct 25, 2006'
    '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'
    '%B %d %Y', '%B %d, %Y',            # 'October 25 2006', 'October 25, 2006'
    '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
]

class loginform(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'validate'}),required=True)
    loginpassword=forms.CharField(widget=forms.PasswordInput(attrs={'class':'validate'}),required=True)
    remember=forms.BooleanField(required=False)

class UserForm(forms.ModelForm):
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput(attrs={'class':'validate form-control'}),required=True)
    def clean(self):
        cleaned_data = super(UserForm,self).clean()
        if  self.cleaned_data['ConfirmPassword'] != self.cleaned_data['password']:
            raise forms.ValidationError({'password':["*Passwords Don't match"]})
        return self.cleaned_data
    class Meta:
        model = User
        fields = ('first_name', 'username', 'password','last_name')
        widgets = {
            'username':forms.EmailInput(attrs={'class':'validate form-control'}),
            'first_name':forms.TextInput(attrs={'class':'validate form-control'}),
            'password':forms.PasswordInput(attrs={'class':'validate form-control'}),
            'last_name':forms.TextInput(attrs={'class':'validate form-control' }),
            }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = logindatabase
        fields = ('Gender','Birthdate')
        widgets = {
            'Birthdate':forms.DateInput(format=dateformat,attrs={'class':'datepicker form-control','Placeholder':'Birthdate'}),
            'Gender':forms.RadioSelect(attrs={'class':'form-control','data-toggle':'radio'}),
             }

       
    

lab10/Feeder35/adminuser/views.py
from django.shortcuts import render

# Create your views here.

lab10/Feeder35/login/views.py
from django.shortcuts import render
from login.models import logindatabase
from django.contrib.auth import authenticate, login
from forms import loginform,UserForm,UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login,logout
from adminuser.models import Student,Courses,Feedbacks,Assignment
from adminuser.forms import CourseProfileForm,feedbackform,student
from django.forms import formset_factory

def registerpage(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/adminuser')
    else:
        active={'logintab':False,'registertab':True}
        registered=""
        if request.method == 'POST':
            register=UserForm(request.POST)
            registerprofile=UserProfileForm(request.POST)
            if register.is_valid() and registerprofile.is_valid():
                newuser=register.save(commit=False)
                newuser.set_password(register.cleaned_data['password'])
                newuser.email=newuser.username
                newuser.save()
                newuser_extra=registerprofile.save(commit=False)
                newuser_extra.user=newuser
                newuser_extra.save()
                register=UserForm()
                registerprofile=UserProfileForm()
                loginformobject=loginform()
                registered="You have been Registered . Please check your mail"
                return render(request,'loginpage.html',{'register':register,'registerprofile':registerprofile,'loginformobject':loginformobject,'active':active,'registered':registered})
        else:
            register=UserForm()
            registerprofile=UserProfileForm()
        loginformobject=loginform()
        return render(request,'loginpage.html',{'register':register,'registerprofile':registerprofile,'loginformobject':loginformobject,'active':active,'registered':registered})


def loginpage(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/adminuser')
    else:
        active={'logintab':True,'registertab':False}
        accesserror=''
        if request.method == 'POST':
            loginformobject=loginform(request.POST)
            if loginformobject.is_valid():
                useraccess = authenticate(username=loginformobject.cleaned_data['username'],password=loginformobject.cleaned_data['loginpassword'])
                if useraccess:
                    if useraccess.is_active:
                        login(request, useraccess)
                        if useraccess.is_staff:
                            return HttpResponseRedirect('/adminuser')
                        else:
                            return HttpResponse('Instructor logged in site under construction')
                    else:
                        accesserror="Your account is disabled.Please contact administrator"
                        return HttpResponseRedirect("/login")
                else:
                    if accesserror == '':
                        accesserror='*Please enter valid Username and Password'
        else:
            loginformobject=loginform()
        register=UserForm()
        registerprofile=UserProfileForm()
        return render(request,'loginpage.html',{'register':register,'registerprofile':registerprofile,'loginformobject':loginformobject,'accesserror':accesserror,'active':active})

            


  

lab10/Feeder35/login/templates/loginpage.html
  {% load staticfiles %}
  {% load socialaccount %}
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}"  media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static 'css/loginpage.css' %}"  media="screen,projection"/>
      
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper  blue lighten-1">
            <a href="#" class="brand-logo center">Welcome To Feedr</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'login' %}">Login</a></li>
            </ul>
            </div>
        </nav>
        <div class="height"></div>
           <div class="row">
                <div class="col l6 m10 s10 offset-l3 offset-m1 offset-s1">       
                         <div class="row">
                           <div class="col l10">
                               <ul class="tabs">
                                    <li class="tab col l6"><a {% if active.logintab %} class="active"  {% endif %} href="#login">Login</a></li>
                                    <li class="tab col l6"><a  {% if active.registertab %} class="active" {% endif %} href="#register">Register</a></li>
                                </ul>
                            </div>
                         </div>
                         
                         
                         <div class="row" id="login" >
                            <div class="row loginside">
                                <div class="col l12">
                                    <form action="{% url 'login' %}" method="POST" class="col l12">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="input-field col l8 m10">
                                                {{loginformobject.username}}
                                                <label for="first_name">Email-Id</label>
                                            </div>
                                        </div>
                                        <div class="row error">
                                            <div class="col l6">
                                                {{loginformobject.username.errors}}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col l8 m10">
                                                {{loginformobject.loginpassword}}
                                                <label for="password">Password</label>
                                            </div>
                                        </div>
                                        <div class="row error">
                                            <div class="col l6">
                                                {{loginformobject.loginpassword.errors}}
                                            </div>
                                        </div>
                                         <p>
                                            {{loginformobject.remember}}
                                            <label for="id_remember">Remember me</label>
                                         </p>
                                         <div class="row error">
                                            <div class="col l6">
                                                {{loginformobject.remember.errors}}
                                            </div>
                                        </div>
                                        <div class="error">
                                            <p>{{accesserror}}</p>
                                        </div>
                                         <button class="btn waves-effect waves-light " type="submit" name="action">Submit
                                            <i class="material-icons right">send</i>
                                        </button>
                                    </form>
                                </div>
                                <div class="row">
                                    <div class="col l12 m12 s12 divider"></div>
                                </div>
                                 <div class="row">
                                 <a href="{% provider_login_url "facebook" method="oauth2" %}">
                                  <button class="btn waves-effect waves-light light-blue btn-large" type="submit" name="action">Login with Facebook
                                                <i class="material-icons right">send</i>
                                    </button>
                                </a>
                                <a href="{% provider_login_url "google" method="oauth2" %}">
                                    <button class="btn waves-effect waves-light red btn-large" type="submit" name="action">Login with Google
                                                <i class="material-icons right">send</i>
                                    </button>
                                </a>
                                </div>
                            </div>
                         </div>
                         
                            
                          <div id="register" class="col s12 m12">
                              <form action="{% url 'registerpage' %}" method="POST" class="col s12">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="input-field col s6">
                                    {{register.first_name}}
                                    <label for="last_name">First Name</label>
                                    </div>
                                    <div class="input-field col s6">
                                    {{register.last_name}}
                                    <label for="first_name">Last Name</label>
                                    </div>
                                </div>
                                <div class="row error">
                                    {% if register.first_name.errors %}
                                    <div class="col s6">
                                    <p class="error">{{register.first_name.errors}}</p>
                                    </div>
                                    {% endif %}
                                     {% if register.last_name.errors %}
                                    <div class="col s6">
                                    <p class="error">{{register.last_name.errors}}</p>
                                    </div>
                                    {% endif %}
                                </div>
                                 <div class="row">
                                    <div class="input-field col s6">
                                    {{register.password}}
                                    <label for="password">Password</label>
                                    </div>
                                    <div class="input-field col s6">
                                    <!--<input id="password" type="password" class="validate">-->
                                    {{register.ConfirmPassword}}
                                    <label for="password"> Confirm Password</label>
                                    </div>
                                </div>
                                <div class="row error">
                                    {% if register.password.errors %}
                                    <div class="col s10">
                                    <p class="error">{{register.password.errors}}</p>
                                    </div>
                                    {% endif %}
                                    {% if register.ConfirmPassword.errors %}
                                    <div class="col s6">
                                    <!--<input id="password" type="password" class="validate">-->
                                    <p class="error">{{register.Confirm_Password.errors}}</p>
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="row">
                                    <div class="input-field col s6">
                                     <!--<input type="date" class="datepicker" id="date" placeholder="Birthday">-->
                                     {{registerprofile.Birthdate}}
                                    </div>
                                    <div class="input-field col s6">
                                    <!--<input id="email" type="email" class="validate">-->
                                    {{register.username}}
                                    <label for="email">Email</label>
                                    </div>
                                </div>
                                <div class="row error">
                                    {% if registerprofile.BirthDate.errors %}
                                    <div class="col s4">
                                    <p class="error">{{registerprofile.Birthdate.errors}}</p>
                                    </div>
                                    {% endif %}
                                    {% if register.username.errors %}
                                    <div class="col s8">
                                    <p class="error">Email-Id already registered</p>
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="row">
                                    <p>
                                       {{registerprofile.Gender.0.tag}}
                                       <label for="id_Gender_0">Male</label>
                                    </p>
                                     <p>
                                       {{registerprofile.Gender.1.tag}}
                                       <label for="id_Gender_1">Female</label>
                                    </p>
                                </div>
                                <div class="row">
                                    {% if registerprofile.Gender.errors %}
                                    <div class="col s6">
                                    <p class="error">{{registerprofile.Gender.errors}}</p>
                                    </div>
                                    {% endif %}
                                </div>
                                 <button class="btn waves-effect waves-light " type="submit" name="action">Sign Up
                                            <i class="material-icons right">send</i>
                                 </button>
                                 <div class="row">
                                     <p style="color:blue">{{registered}}</p>
                                 </div>
                                </form>
                          </div>
            </div>
           </div>
  
    </body>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>
    <script
    >$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year
    format: 'yyyy-mm-dd'
  });
  </script>

  </html>

lab10/Feeder35/login/templates/sampleform.html
  {% load staticfiles %}
<html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/datedropper.js' %}"></script>
        
        <link type="text/css" rel="stylesheet" href="{% static 'css/datedropper.css' %}"  media="screen,projection"/>        
      <!--Import materialize.css-->
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <form action="{% url 'adminpage' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
    </body>
<script>$( ".departure" ).dateDropper();</script>
</html>